### ISSUE TITLE
Overview should mention that the target is standard C (ClightTSO)

### ISSUE THREAD

**Issue by MaxBarraclough** [microsoft/Armada#2]
I suggest that the Overview section of the README.md should mention that Armada targets standard C (specifically the ClightTSO subset). At first I got the impression Armada was less ambitious than it really is.

(I heard of Armada through [this HackerNews thread](https://news.ycombinator.com/item?id=24002430).)

**Comment by jaylorch** [comment]
Good suggestion, thanks!  I'll fix that.
